# Generated by Django 4.2.2 on 2023-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("primera", "0002_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
