# Generated by Django 4.2.2 on 2023-06-15 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("primera", "0003_alter_author_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"permissions": (("es_miembro_1", "Es miembro con prioridad 1"),)},
        ),
    ]
