# Generated by Django 4.2.2 on 2023-06-16 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("primera", "0004_alter_author_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "permissions": (("es_miembro_1", "Es miembro con prioridad 1"),),
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Libro", "verbose_name_plural": "Libros"},
        ),
        migrations.AddField(
            model_name="author",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
